# Build step

FROM python:3

WORKDIR /usr/src/app

COPY . .

WORKDIR /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt


WORKDIR "/usr/src/app/app"
ENTRYPOINT [ "flask", "run", "-h", "0.0.0.0" ]


EXPOSE 5000

