"""

Revision ID: 281244f5856d
Revises: f9d5988997f6
Create Date: 2019-05-21 07:52:09.864593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281244f5856d'
down_revision = 'f9d5988997f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'user', ['ArticleAuthor'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'article', 'language', ['Language'], ['Lang'], use_alter=True)
    op.create_foreign_key(None, 'comment', 'article', ['FromArticle'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'comment', 'language', ['Language'], ['Lang'], use_alter=True)
    op.create_foreign_key(None, 'comment', 'user', ['Author'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'emotionScore', 'comment', ['CommentID'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'keywords', 'comment', ['CommentID'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.drop_constraint(None, 'emotionScore', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
