"""

Revision ID: b3a48d86e3f5
Revises: 
Create Date: 2019-05-09 17:32:53.327070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a48d86e3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserLogin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('LoginProvider', sa.String(length=255), nullable=True),
    sa.Column('ProviderUserID', sa.String(length=255), nullable=True),
    sa.Column('ProviderUserName', sa.String(length=255), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('UserGlobalID', sa.String(length=255), nullable=False),
    sa.Column('UserName', sa.String(length=255), nullable=True),
    sa.Column('UserUrl', sa.TEXT(), nullable=True),
    sa.Column('UserMedia', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['UserLogin.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id', 'UserGlobalID'),
    sa.UniqueConstraint('UserGlobalID')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('FromUserID', sa.Integer(), nullable=False),
    sa.Column('ToUserGlobalID', sa.String(length=255), nullable=False),
    sa.Column('CommentString', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['FromUserID'], ['UserLogin.id'], use_alter=True),
    sa.ForeignKeyConstraint(['ToUserGlobalID'], ['UserProfile.UserGlobalID'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentEndorse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('CommentID', sa.Integer(), nullable=False),
    sa.Column('EndorseBy', sa.Integer(), nullable=False),
    sa.Column('Score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CommentID'], ['comment.id'], use_alter=True),
    sa.ForeignKeyConstraint(['EndorseBy'], ['UserLogin.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endorsement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userEndorse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('UserGlobalID', sa.String(length=255), nullable=False),
    sa.Column('EndorseBy', sa.Integer(), nullable=False),
    sa.Column('Score', sa.Integer(), nullable=True),
    sa.Column('EndorseID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EndorseBy'], ['UserLogin.id'], use_alter=True),
    sa.ForeignKeyConstraint(['EndorseID'], ['endorsement.id'], use_alter=True),
    sa.ForeignKeyConstraint(['UserGlobalID'], ['UserProfile.UserGlobalID'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userEndorse')
    op.drop_table('endorsement')
    op.drop_table('commentEndorse')
    op.drop_table('comment')
    op.drop_table('UserProfile')
    op.drop_table('UserLogin')
    # ### end Alembic commands ###
