"""

Revision ID: f9d5988997f6
Revises: 
Create Date: 2019-05-21 07:52:05.821124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d5988997f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('ArticleUrl', sa.String(length=255), nullable=False),
    sa.Column('ArticleTitle', sa.String(length=255), nullable=True),
    sa.Column('ArticleAuthor', sa.Integer(), nullable=False),
    sa.Column('Content', sa.TEXT(), nullable=True),
    sa.Column('Language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ArticleAuthor'], ['user.id'], use_alter=True),
    sa.ForeignKeyConstraint(['Language'], ['language.Lang'], use_alter=True),
    sa.PrimaryKeyConstraint('id', 'ArticleUrl'),
    sa.UniqueConstraint('ArticleUrl')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('FromArticle', sa.Integer(), nullable=False),
    sa.Column('Author', sa.Integer(), nullable=False),
    sa.Column('CommentString', sa.TEXT(), nullable=True),
    sa.Column('CommentTime', sa.DateTime(), nullable=True),
    sa.Column('CommentPush', sa.String(length=5), nullable=True),
    sa.Column('Language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['Author'], ['user.id'], use_alter=True),
    sa.ForeignKeyConstraint(['FromArticle'], ['article.id'], use_alter=True),
    sa.ForeignKeyConstraint(['Language'], ['language.Lang'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotionScore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('CommentID', sa.Integer(), nullable=False),
    sa.Column('Score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['CommentID'], ['comment.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('CommentID', sa.Integer(), nullable=False),
    sa.Column('Phase', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['CommentID'], ['comment.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('Lang', sa.String(length=10), nullable=False),
    sa.Column('Iso6391Name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', 'Lang'),
    sa.UniqueConstraint('Lang')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('UserName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'UserName'),
    sa.UniqueConstraint('UserName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('language')
    op.drop_table('keywords')
    op.drop_table('emotionScore')
    op.drop_table('comment')
    op.drop_table('article')
    # ### end Alembic commands ###
